# Generated by Django 5.0.1 on 2026-05-02 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("plates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GateEvent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "camera_id",
                    models.CharField(
                        help_text="Camera identifier (e.g., 'entry', 'exit')",
                        max_length=20,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("entry", "Entry"), ("exit", "Exit")],
                        help_text="Direction of vehicle movement: 'entry' or 'exit'",
                        max_length=10,
                    ),
                ),
                (
                    "plate_raw",
                    models.CharField(
                        blank=True,
                        help_text="Raw plate number as detected by OCR before operator confirmation",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "plate_confirmed",
                    models.CharField(
                        blank=True,
                        help_text="Confirmed plate number after operator approval/editing",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="OCR confidence score (0.0000 to 1.0000)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "plate_image_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to stored plate image file",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "was_edited",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the operator manually edited the detected plate number",
                    ),
                ),
                (
                    "was_auto_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the event was auto-approved after timeout (15 seconds)",
                    ),
                ),
                (
                    "was_rejected",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the operator rejected this detection",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when gate event was recorded (UTC)",
                    ),
                ),
                (
                    "matched_plate",
                    models.ForeignKey(
                        blank=True,
                        help_text="Plate registration associated with this detection (if registered)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gate_events",
                        to="plates.plate",
                    ),
                ),
                (
                    "matched_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User associated with the detected plate (if registered)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matched_gate_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        help_text="Operator who processed this gate event",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_gate_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gate Event",
                "verbose_name_plural": "Gate Events",
                "db_table": "gate_events",
                "default_permissions": ("add", "view"),
            },
        ),
        migrations.CreateModel(
            name="ParkingSession",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "guest_plate_number",
                    models.CharField(
                        blank=True,
                        help_text="Plate number for guest vehicles (normalized format)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "entry_time",
                    models.DateTimeField(
                        help_text="Timestamp when vehicle entered (UTC)"
                    ),
                ),
                (
                    "exit_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when vehicle exited (UTC)",
                        null=True,
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Total parking duration in minutes",
                        null=True,
                    ),
                ),
                (
                    "fee_charged",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Fee charged in Toman",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("parked", "Parked"),
                            ("completed", "Completed"),
                            ("unpaid", "Unpaid"),
                            ("waived", "Waived"),
                            ("flagged", "Flagged"),
                        ],
                        default="parked",
                        help_text="Current session status",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("wallet", "Wallet"),
                            ("cash", "Cash"),
                            ("waived", "Waived"),
                        ],
                        help_text="Payment method used (if paid)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional notes from operator", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when session was created",
                    ),
                ),
                (
                    "collected_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Operator who collected cash payment or waived fee",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collected_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entry_event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Gate event that created this session",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entry_sessions",
                        to="parking.gateevent",
                    ),
                ),
                (
                    "exit_event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Gate event that closed this session",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exit_sessions",
                        to="parking.gateevent",
                    ),
                ),
                (
                    "plate",
                    models.ForeignKey(
                        blank=True,
                        help_text="Registered plate (if user is registered)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parking_sessions",
                        to="plates.plate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parking Session",
                "verbose_name_plural": "Parking Sessions",
                "db_table": "parking_sessions",
            },
        ),
        migrations.AddField(
            model_name="gateevent",
            name="session",
            field=models.ForeignKey(
                blank=True,
                help_text="Parking session associated with this gate event",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gate_events",
                to="parking.parkingsession",
            ),
        ),
        migrations.AddIndex(
            model_name="parkingsession",
            index=models.Index(
                condition=models.Q(("status", "completed"), _negated=True),
                fields=["status"],
                name="parking_sess_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="parkingsession",
            index=models.Index(
                fields=["-entry_time"], name="parking_ses_entry_t_564b17_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="parkingsession",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("plate__isnull", False),
                    ("guest_plate_number__isnull", False),
                    _connector="OR",
                ),
                name="parking_sess_plate_or_guest",
            ),
        ),
        migrations.AddIndex(
            model_name="gateevent",
            index=models.Index(
                fields=["plate_confirmed"], name="gate_events_plate_c_c85b2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gateevent",
            index=models.Index(
                fields=["-created_at"], name="gate_events_created_97d549_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gateevent",
            index=models.Index(
                fields=["direction", "-created_at"],
                name="gate_events_directi_27799d_idx",
            ),
        ),
    ]
