# Generated by Django 4.2.30 on 2026-05-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Standard", max_length=100)),
                (
                    "rate_per_hour",
                    models.DecimalField(
                        decimal_places=0,
                        default=5000,
                        help_text="Hourly rate in Toman",
                        max_digits=12,
                    ),
                ),
                (
                    "daily_cap",
                    models.DecimalField(
                        decimal_places=0,
                        default=40000,
                        help_text="Maximum charge per session in Toman",
                        max_digits=12,
                    ),
                ),
                (
                    "grace_period_minutes",
                    models.PositiveIntegerField(
                        default=10, help_text="Free parking duration in minutes"
                    ),
                ),
                (
                    "student_discount_percent",
                    models.PositiveSmallIntegerField(
                        default=80,
                        help_text="Percent of fee charged for students (80 = 20% discount)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this rate profile is currently in use",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rate configuration",
                "verbose_name_plural": "Rate configurations",
                "db_table": "rate_configs",
                "ordering": ["-is_active", "-updated_at"],
            },
        ),
    ]
