# Generated by Django 4.2.30 on 2026-07-18 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("parking", "0004_operationalstate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationalstate",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="DetectionFail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fail_type",
                    models.CharField(
                        choices=[
                            ("ocr_invalid_format", "OCR invalid Iranian format"),
                            ("ocr_empty", "OCR empty / below threshold"),
                            (
                                "operator_confirmed_miss",
                                "Operator confirmed miss (no bbox)",
                            ),
                        ],
                        max_length=32,
                    ),
                ),
                ("raw_ocr", models.CharField(blank=True, default="", max_length=64)),
                (
                    "validation_error",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "plate_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "char_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                ("bbox", models.JSONField(blank=True, null=True)),
                ("camera_id", models.CharField(max_length=32)),
                (
                    "direction",
                    models.CharField(
                        choices=[("entry", "Entry"), ("exit", "Exit")],
                        default="entry",
                        max_length=10,
                    ),
                ),
                (
                    "full_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="detection_fails/%Y/%m/%d/"
                    ),
                ),
                (
                    "crop_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="detection_fails/%Y/%m/%d/crops/",
                    ),
                ),
                (
                    "local_data_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Relative path under Core/data_fails/",
                        max_length=512,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("corrected", "Corrected"),
                            ("not_a_plate", "Not a plate"),
                            ("processed", "Processed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("not_a_plate", models.BooleanField(default=False)),
                (
                    "label_ground_truth",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("sharpness", models.FloatField(blank=True, null=True)),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gate_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_detection_fails",
                        to="parking.gateevent",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_detection_fails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Detection fail",
                "verbose_name_plural": "Detection fails",
                "db_table": "detection_fails",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["review_status", "-created_at"],
                        name="detection_f_review__6db05c_idx",
                    ),
                    models.Index(
                        fields=["fail_type", "-created_at"],
                        name="detection_f_fail_ty_526e26_idx",
                    ),
                ],
            },
        ),
    ]
