# Generated by Django 4.2.30 on 2026-07-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0005_detectionfail"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectionfail",
            name="has_scene_b",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="detectionfail",
            name="scene_b_image",
            field=models.ImageField(
                blank=True,
                help_text="Scene B — delayed RTSP frame or padded bbox context",
                null=True,
                upload_to="detection_fails/%Y/%m/%d/scene_b/",
            ),
        ),
        migrations.AddField(
            model_name="detectionfail",
            name="scene_b_source",
            field=models.CharField(
                blank=True,
                default="",
                help_text="rtsp_delayed | padded_bbox | empty",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="detectionfail",
            name="full_image",
            field=models.ImageField(
                blank=True,
                help_text="Scene A — frame at detection-fail time",
                null=True,
                upload_to="detection_fails/%Y/%m/%d/",
            ),
        ),
    ]
