# Generated by Django 4.2.30 on 2026-07-20 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0007_sync_and_media_foundations"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="eventmedia",
            new_name="event_media_upload__b49862_idx",
            old_name="event_media_upload__7a3c1a_idx",
        ),
        migrations.RenameIndex(
            model_name="syncoutbox",
            new_name="sync_outbox_status_283bbb_idx",
            old_name="sync_outbox_status_4e2b1c_idx",
        ),
        migrations.RenameIndex(
            model_name="syncoutbox",
            new_name="sync_outbox_payload_2954bc_idx",
            old_name="sync_outbox_payload_9f1a2b_idx",
        ),
    ]
