# Generated by Django 4.2.30 on 2026-07-20 19:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("site_id", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(default="Main parking", max_length=200)),
                ("capacity", models.PositiveIntegerField(default=100)),
                ("last_ingest_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="replica.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SiteSyncCursor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_event_at", models.DateTimeField(blank=True, null=True)),
                ("last_reconcile_at", models.DateTimeField(blank=True, null=True)),
                ("events_received", models.PositiveIntegerField(default=0)),
                ("images_received", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_cursor",
                        to="replica.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReplicaGateEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_uuid", models.UUIDField()),
                (
                    "occurred_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("direction", models.CharField(max_length=10)),
                ("camera_id", models.CharField(blank=True, default="", max_length=64)),
                ("plate_raw", models.CharField(blank=True, default="", max_length=32)),
                (
                    "plate_confirmed",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("was_edited", models.BooleanField(default=False)),
                ("was_auto_approved", models.BooleanField(default=False)),
                ("was_rejected", models.BooleanField(default=False)),
                (
                    "session_uuid",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "operator_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "matched_user_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("local_gate_event_id", models.IntegerField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gate_events",
                        to="replica.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReplicaEventMedia",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_uuid", models.UUIDField(db_index=True)),
                (
                    "session_uuid",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("scene_a", "Scene A"),
                            ("scene_b", "Scene B"),
                            ("crop", "Crop"),
                            ("thumbnail", "Thumbnail"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "object_key",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                ("upload_status", models.CharField(default="uploaded", max_length=20)),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_media",
                        to="replica.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReplicaDetectionFail",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("fail_uuid", models.UUIDField()),
                ("fail_type", models.CharField(blank=True, default="", max_length=64)),
                (
                    "review_status",
                    models.CharField(blank=True, default="pending", max_length=32),
                ),
                ("camera_id", models.CharField(blank=True, default="", max_length=64)),
                ("direction", models.CharField(blank=True, default="", max_length=10)),
                ("raw_ocr", models.CharField(blank=True, default="", max_length=64)),
                ("was_corrected", models.BooleanField(default=False)),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detection_fails",
                        to="replica.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(blank=True, default="", max_length=100)),
                ("direction", models.CharField(blank=True, default="", max_length=10)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gates",
                        to="replica.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("camera_id", models.CharField(max_length=64)),
                ("name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "gate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="replica.gate",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cameras",
                        to="replica.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReplicaParkingSession",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("session_uuid", models.UUIDField()),
                (
                    "plate_number",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                ("user_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "entry_time",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("exit_time", models.DateTimeField(blank=True, null=True)),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                ("fee_charged", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(db_index=True, default="parked", max_length=20),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("entry_event_uuid", models.UUIDField(blank=True, null=True)),
                ("exit_event_uuid", models.UUIDField(blank=True, null=True)),
                (
                    "entry_camera_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "exit_camera_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("local_session_id", models.IntegerField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="replica.site",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["site", "status", "-entry_time"],
                        name="replica_rep_site_id_252839_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="replicaparkingsession",
            constraint=models.UniqueConstraint(
                fields=("site", "session_uuid"), name="replica_session_site_uuid_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="replicagateevent",
            index=models.Index(
                fields=["site", "-occurred_at"], name="replica_rep_site_id_eabd9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="replicagateevent",
            index=models.Index(
                fields=["site", "direction", "-occurred_at"],
                name="replica_rep_site_id_2e7aa2_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="replicagateevent",
            constraint=models.UniqueConstraint(
                fields=("site", "event_uuid"), name="replica_gate_site_uuid_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="replicaeventmedia",
            constraint=models.UniqueConstraint(
                fields=("site", "event_uuid", "image_type"),
                name="replica_media_site_event_type_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="replicadetectionfail",
            constraint=models.UniqueConstraint(
                fields=("site", "fail_uuid"), name="replica_fail_site_uuid_uniq"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gate",
            unique_together={("site", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="camera",
            unique_together={("site", "camera_id")},
        ),
    ]
