# Generated by Django 4.2.30 on 2026-07-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("replica", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="replicaeventmedia",
            name="image_type",
            field=models.CharField(
                choices=[
                    ("scene_a", "Scene A"),
                    ("scene_b", "Scene B"),
                    ("crop", "Crop"),
                    ("thumbnail", "Thumbnail"),
                    ("fail_full", "Fail full"),
                    ("fail_crop", "Fail crop"),
                    ("fail_scene_b", "Fail scene B"),
                ],
                max_length=20,
            ),
        ),
    ]
