# Generated by Django 4.2.30 on 2026-07-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("replica", "0002_alter_replicaeventmedia_image_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="season_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
