# Generated by Django 5.0.1 on 2026-05-02 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "plate_number",
                    models.CharField(
                        help_text="Normalized plate format: [۰-۹]{2}[letter][۰-۹]{3}-[۰-۹]{2}",
                        max_length=20,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the user's primary plate",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this plate has been verified by an operator",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this plate is currently active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when plate was registered",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this plate",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plate",
                "verbose_name_plural": "Plates",
                "db_table": "plates",
                "indexes": [
                    models.Index(
                        condition=models.Q(("is_active", True)),
                        fields=["plate_number"],
                        name="plates_active_plate_idx",
                    ),
                    models.Index(fields=["user"], name="plates_user_id_07696c_idx"),
                    models.Index(
                        fields=["user", "is_primary"], name="plates_user_id_215b8e_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="plate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_primary", True)),
                fields=("user",),
                name="plates_one_primary_per_user",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="plate",
            unique_together={("user", "plate_number")},
        ),
    ]
