# Generated by Django 5.0.1 on 2026-05-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plate",
            name="free_zone",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ANZALI", "Anzali Free Zone"),
                    ("ARAS", "Aras Free Zone"),
                    ("ARVAND", "Arvand Free Zone"),
                    ("KISH", "Kish Free Zone"),
                    ("MAKU", "Maku Free Zone"),
                    ("CHABAHAR", "Chabahar Free Zone"),
                    ("QESHM", "Qeshm Free Zone"),
                ],
                help_text="Free Zone name (only for Free Zone plates)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="plate",
            name="is_free_zone",
            field=models.BooleanField(
                default=False, help_text="Whether this is a Free Zone plate"
            ),
        ),
        migrations.AlterField(
            model_name="plate",
            name="plate_number",
            field=models.CharField(
                help_text="Normalized plate format: National [۰-۹]{2}[letter][۰-۹]{3}-[۰-۹]{2} or Free Zone [۰-۹]{5}-[ZONE]",
                max_length=30,
            ),
        ),
    ]
