# Generated by Django 4.2.30 on 2026-07-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plates", "0002_add_free_zone_support"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plate",
            name="plate_number",
            field=models.CharField(
                help_text="Normalized plate format: National [۰-۹]{2}[letter][۰-۹]{3}-[۰-۹]{2} or Free Zone [۰-۹]{5}-[۰-۹]{2}",
                max_length=30,
            ),
        ),
    ]
