# Generated by Django 5.0.1 on 2026-05-01 22:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Wallet balance in Toman (non-negative)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp of last wallet update"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User who owns this wallet",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
                "db_table": "wallets",
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Transaction amount in Toman (positive)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("topup", "Top-up"),
                            ("fee", "Fee"),
                            ("refund", "Refund"),
                        ],
                        help_text="Transaction type: topup, fee, or refund",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional transaction description",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(
                        blank=True,
                        help_text="Unique reference code for this transaction",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Transaction timestamp"
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed this transaction (operator for top-ups)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        help_text="Wallet this transaction belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet Transaction",
                "verbose_name_plural": "Wallet Transactions",
                "db_table": "wallet_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(fields=["user"], name="wallets_user_id_9fb6cf_idx"),
        ),
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.CheckConstraint(
                check=models.Q(("balance__gte", 0)), name="wallet_balance_non_negative"
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["wallet", "-created_at"], name="wallet_tran_wallet__3d47ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(fields=["type"], name="wallet_tran_type_be1dd4_idx"),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["reference_code"], name="wallet_tran_referen_cc8285_idx"
            ),
        ),
    ]
