# Generated by Django 4.2.30 on 2026-05-16 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("parking", "0002_rateconfig"),
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="session",
            field=models.ForeignKey(
                blank=True,
                help_text="Parking session linked to this transaction (for fee transactions)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wallet_transactions",
                to="parking.parkingsession",
            ),
        ),
    ]
